In [15]:
import numpy as np

1. Given a 2D list, create a numpy 2D array using it.
2. Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3. Print the Numpy array.

In [16]:
a=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1. Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
2. Print the elements of array.

In [17]:
a=np.zeros(10,dtype=int)
a[4]=1
for i in a:
    print(i,end=" ")

0 0 0 0 1 0 0 0 0 0 

1. Create an array with values ranging consecutively from 9 to 49 (both inclusive).
2. Print the Numpy array.

In [18]:
print(np.arange(9,50))

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


1. Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
2. Print the Numpy array.

In [19]:
print(np.eye(5,6,dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


1. You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
2. Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
3. Print the array element.

In [20]:
a = np.linspace(0,5,10)[1:9]
for i in a:
    print(round(i,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
