In [1]:
import numpy as np

1. Given a 2D list, create a numpy 2D array using it.
2. Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3. Print the Numpy array.

In [2]:
a=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1. Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
2. Print the elements of array.