In [28]:
import numpy as np

1. Given a 2D list, create a numpy 2D array using it.
2. Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3. Print the Numpy array.

In [29]:
a=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1. Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
2. Print the elements of array.

In [30]:
a=np.zeros(10,dtype=int)
a[4]=1
for i in a:
    print(i,end=" ")

0 0 0 0 1 0 0 0 0 0 

1. Create an array with values ranging consecutively from 9 to 49 (both inclusive).
2. Print the Numpy array.

In [31]:
print(np.arange(9,50))

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


1. Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
2. Print the Numpy array.

In [32]:
print(np.eye(5,6,dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


1. You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
2. Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
3. Print the array element.

In [33]:
a = np.linspace(0,5,10)[1:9]
for i in a:
    print(round(i,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


1. Given a 2D integer array size (4, 5) with name input_?
2. Print elements of highlighted matrix
3. Output Format :

element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .

In [34]:
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
for i in input_[2,:3]:
    print(i,end=' ')
print()
for i in input_[1:,3]:
    print(i,end=' ')
print()
for i in input_[2:]:
    for j in i:
        print(j,end=' ')
print()
for i in input_[1:3,1:3]:
    for j in i:
        print(j,end=' ')

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

1. Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
2. Print the index of non-zero elements.

In [35]:
import numpy as np
b=np.array([1,2,0,0,4,0])
b1=np.where(b!=0)
for i in b1[0]:
    print(i,end=" ")

0 1 4 

1. Given an integer array of size 10. Print the index of elements which are multiple of 3.
2. Note: Generate the following array
3. array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
4. Print the index of elements.

In [36]:
import numpy as np
b=np.arange(1,20,2)
new_arr=np.where(b%3==0)
for i in new_arr[0]:
    print(i,end=" ")

1 4 7 

1. Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
2. Note: Generate the following array
3. array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [37]:
import numpy as np
a=np.arange(1,11)
a[a%2!=0]=-1
for i in a:
    print(i,end=" ")

-1 2 -1 4 -1 6 -1 8 -1 10 

1. Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
2. Note: Generate the following array
3. array([11, 2, 13, 4, 15, 6, 27, 8, 19])
4. Print the Numpy array.

In [38]:
import numpy as np
arr=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
arr[np.argmax(arr)]=0
for i in arr:
    print(i)

11
2
13
4
15
6
0
8
19


1. Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
2. Note: Generate the following array  array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
3. Print the Numpy array.

In [39]:
import numpy as np
a=np.arange(1,11)
a[np.logical_and(a>=3 , a<=8)]*=-1
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


1. Problem Statemnt:
2. Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
3. Print the Numpy array.
Output Format :
age1 height1 
age2 height2 

In [40]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

np_age=age[height>155]
np_heigth=height[height>155]

for i in range(len(np_heigth)):
    print(np_age[i],np_heigth[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


1. Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
2. That means, we should re-arrange complete row based on 2nd columns' values.
3. Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
4. Print the 2D array in sorted order.
5. Note you have to generate the 2D Array.Here 2nd column means column present at index 1.

In [43]:
import numpy as np
arr=np.array([[21 ,20, 19, 18, 17],
                [16, 15, 14, 13, 12],
                [11 ,10 , 9 , 8 , 7],
                [ 6 , 5 , 4  ,3 , 2]])
print(np.sort(arr,axis=0))

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


1. Find value of killed column only where country == ‘United States’?
2. Print 0 in place of missing values.
3. Print count of Killed as integer value.

In [47]:
import numpy as np
import csv
with open('terrorismData.csv',encoding='utf-8') as file_obj:
    file=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    country=[]

    for row in file:
       killed.append(row['Killed'])
       country.append(row['Country'])
    
np_killed=np.array(killed)
np_killed[np_killed=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_country=np.array(country)
b=np_country=='United States'
ans=np_killed[b]

for i in ans:
    print(int(i))

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
4
0
1
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0


1. Find total number of people killed from USA?
2. Note: Some columns of killed are empty so replace them by 0.
3. Print count of Killed as integer value.

In [49]:
import numpy as np
import csv
with open('terrorismData.csv',encoding='utf-8') as file_obj:
    file=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    country=[]

    for row in file:
       killed.append(row['Killed'])
       country.append(row['Country'])
    
np_killed=np.array(killed)
np_killed[np_killed=='']='0.0'

np_killed=np.array(np_killed,dtype=float)
np_country=np.array(country)
b=np_country=='United States'
ans=np_killed[b]

print(int(ans.sum()))

3771


1. Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
2. Print count of NumberOFAttack as integer value.

In [61]:
import numpy as np
import csv
with open('terrorismData.csv',encoding='utf-8') as file_obj:
    file=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    day=[]

    for row in file:
       killed.append(row['Killed'])
       day.append(row['Day'])
    
np_killed=np.ones(len(killed),dtype=int)
np_day=np.array(day,dtype=float)
ans=np_killed[(np_day>=10) & (np_day<=20)]

print(int(ans.sum()))

66330


1. Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
2. Note Ignore the case where day is 0
3. Print count of NumberOFAttack as integer value.

In [65]:
import numpy as np
import csv

file=open("terrorismData.csv",encoding='utf-8')
data=csv.DictReader(file,skipinitialspace=True)
Day=[]
Month=[]
Year=[]

for row in data:
    Day.append(row['Day'])
    Month.append(row['Month'])
    Year.append(row['Year'])
    
np_Day=np.array(Day,dtype=int)
np_Month=np.array(Month,dtype=int)
np_Year=np.array(Year,dtype=int)

np_bool =(np_Day>=1) &(np_Day<=31) & (np_Year==2010) &(np_Month==1)

print(np.sum(np_bool))

271


1. As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
2. In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
3. So find out the attack in this period in which maximum casualties happened.
4. Print the count of casualties (as integer), city in which that attack happened and name of attack group.
5. Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.
6. Casualty City TerroristGroup (Print)

In [67]:
import numpy as np
import csv
with open('terrorismData.csv', encoding = "utf-8") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    wounded=[]
    killed=[]
    grp=[]
    city=[]
    for row in file_data:
        if row['Year']=='1999':
             if row["Month"]=="5" or row["Month"]=="6" or row["Month"]=="7":
                    if row['State']=='Jammu and Kashmir':
                            if "Unknown" not in row["City"]:
                                if "Unknown" not in row["Group"]:
                                    killed.append(row['Killed'])
                                    wounded.append(row['Wounded'])
                                    city.append(row['City'])
                                    grp.append(row['Group'])
killed = np.array(killed)
wounded = np.array(wounded)
city = np.array(city)
grp=np.array(grp)
 
killed[killed == ""] = "0.0"
wounded[wounded == ""] = "0.0"
killed = np.array(killed, dtype = float)
wounded = np.array(wounded, dtype = float)
# taking sum and then printing the required values
casualty = (killed + wounded)
max_casualty = (int)(casualty.max())
# getting the INDEX of max casualty, this is for putting the required index in city and group
max_casualty_arg = casualty.argmax()
print(max_casualty,city[max_casualty_arg],grp[max_casualty_arg])

22 Kargil District Separatists


1. Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
2. Note: Casualty=Killed +Wounded
3. Print count of Casualty as integer value.

In [76]:
import numpy as np
import csv
with open('terrorismData.csv', encoding = "utf-8") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    wounded=[]
    killed=[]
    state=[]
    for row in file_data:
        wounded.append(row['Wounded'])
        killed.append(row['Killed'])
        state.append(row['State'])
    killed=np.array(killed)
    wounded=np.array(wounded)
    killed[killed == ""] = "0.0"
    wounded[wounded == ""] = "0.0"
    killed = np.array(killed, dtype = float)
    wounded = np.array(wounded, dtype = float)
    caus=killed+wounded
    state=np.array(state)
    b=((state=='Jharkhand') | (state=='Odisha') | (state=='Andhra Pradesh') | (state=='Chhattisgarh'))
    caus=caus[b]
    print(int(caus.sum()))


5628


1. Find top 5 Indian Cities which has most number of casualties ?
2. Print top 5 cities along with total casualties in that city. Print count of Casualty as integer value.
3. Note: Ignoring the City which is Unknown.
4. Casualty = Killed + Wounded.

In [77]:
import numpy as np
import csv

with open('terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    for row in file_data:
        if 'India' in row['Country'] and 'Unknown' not in row['City']:
            city.append(row['City'])
            wounded.append(row['Wounded'])
            killed.append(row['Killed'])
    np_wounded=np.array(wounded)
    np_killed=np.array(killed)
    np_city=np.array(city)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    np_killed=np.array(np_killed, dtype='float')
    np_wounded=np.array(np_wounded, dtype='float')
    np_casuality=np.array(np_wounded+np_killed, dtype='int')
    citydic={}
    for i in range(len(np_city)):
        if np_city[i] in citydic:
            citydic[np_city[i]]+=np_casuality[i]
        else:
            citydic[np_city[i]]=np_casuality[i]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


1. Find the most frequent day of attack in a terrorismDataset ?
2. Note: Here np.unique can be used.
3. Print count of frequent day and number of attack as Integer value.
4. Day NumberOFAttack

In [78]:
import numpy as np
import csv

with open('terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    
    day=[]
    for row in file_data:
        day.append(row['Day'])
    np_day=np.array(day, dtype='int')
    day, count=np.unique(np_day, return_counts=True)
    print(day[np.argmax(count)], count[np.argmax(count)])

15 6500
